-- ============================================================
-- SISPRO MIGRATION TEST — PARTE 1: Creación DB + Fases A y B
-- Base simulada: bdsispro_test
-- Generado: 2026-02-27 | Fuente: BD_SISPRO_INFO.md
-- RESTRICCIÓN: No modifica bdsispro ni archivos de MenuCosto
-- ============================================================
DROP DATABASE IF EXISTS bdsispro_test;
CREATE DATABASE bdsispro_test CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci;
USE bdsispro_test;
-- ============================================================
-- FASE A — Datos de referencia invariantes
-- ============================================================
CREATE TABLE empresas (
    RUT_EMPRESA INT NOT NULL,
    DIGITO VARCHAR(1),
    NOMBRE_EMPRESA VARCHAR(50),
    CODIGO VARCHAR(3),
    SIGLA VARCHAR(50),
    GIRO VARCHAR(80),
    RUT_REPRESEN INT,
    DV_REPRESEN VARCHAR(1),
    NOMBRE_REPRESEN VARCHAR(50),
    DIRECCION VARCHAR(100),
    COMUNA VARCHAR(50),
    CIUDAD VARCHAR(50),
    TELEFONO VARCHAR(20),
    FAX VARCHAR(20),
    CORREO VARCHAR(80),
    CODIGO_ACTIVIDAD VARCHAR(20),
    PRIMARY KEY (RUT_EMPRESA)
) ENGINE = InnoDB;
CREATE TABLE parametros (
    EMPRESA VARCHAR(3) NOT NULL,
    TIPO VARCHAR(10) NOT NULL,
    CODIGO INT NOT NULL,
    DESCRIPCION VARCHAR(50),
    ATRIBUTO1 VARCHAR(50),
    ATRIBUTO2 VARCHAR(50),
    ATRIBUTO3 DOUBLE,
    ATRIBUTO4 DOUBLE,
    PRIMARY KEY (EMPRESA, TIPO, CODIGO)
) ENGINE = InnoDB;
CREATE TABLE configuracion_sistema (
    Empresa VARCHAR(3) NOT NULL,
    Sistema VARCHAR(10) NOT NULL,
    Por_Iva DOUBLE,
    Ann_Activo INT,
    ControlaInv BIT(1),
    Rut_Nulos INT,
    Rut_Boletas INT,
    NombreFormato VARCHAR(50),
    Primera DATETIME,
    Segunda DATETIME,
    Tercera DATETIME,
    Local INT,
    Bodega VARCHAR(20),
    Vendedor INT,
    PorCostoBE DOUBLE,
    Dias_Compra1 INT,
    Dias_Compra2 INT,
    Dias_Corte1 INT,
    Dias_Corte2 INT,
    Dias_Termino1 INT,
    Dias_Termino2 INT,
    CostoFlete DOUBLE,
    CostoHilos DOUBLE,
    CostoFijo DOUBLE,
    CostoEtiqueta DOUBLE,
    CostoEmbalaje DOUBLE,
    ValorFijo DOUBLE,
    CostosinGratif DOUBLE,
    CostoconGratif DOUBLE,
    PRIMARY KEY (Empresa, Sistema)
) ENGINE = InnoDB;
CREATE TABLE locales (
    EMPRESA VARCHAR(3) NOT NULL,
    CODIGO INT NOT NULL,
    DESCRIPCION VARCHAR(50),
    DIRECCION VARCHAR(100),
    COMUNA VARCHAR(50),
    CIUDAD VARCHAR(50),
    TELEFONO VARCHAR(20),
    PRIMARY KEY (EMPRESA, CODIGO)
) ENGINE = InnoDB;
CREATE TABLE cencosto (
    EMPRESA VARCHAR(3) NOT NULL,
    CODIGO INT NOT NULL,
    DESCRIPCION VARCHAR(50),
    PRIMARY KEY (EMPRESA, CODIGO)
) ENGINE = InnoDB;
CREATE TABLE gastos (
    EMPRESA VARCHAR(3) NOT NULL,
    CODIGO VARCHAR(20) NOT NULL,
    DESCRIPCION VARCHAR(50),
    Estado INT,
    PRIMARY KEY (EMPRESA, CODIGO)
) ENGINE = InnoDB;
CREATE TABLE itemgasto (
    EMPRESA VARCHAR(3) NOT NULL,
    CODIGO VARCHAR(20) NOT NULL,
    DESCRIPCION VARCHAR(50),
    PRIMARY KEY (EMPRESA, CODIGO)
) ENGINE = InnoDB;
CREATE TABLE bancos (
    IdBanco INT AUTO_INCREMENT NOT NULL,
    Empresa VARCHAR(3),
    Nombre VARCHAR(60),
    Codigo VARCHAR(10),
    PRIMARY KEY (IdBanco)
) ENGINE = InnoDB;
CREATE TABLE plantillas (
    Empresa VARCHAR(3) NOT NULL,
    Plantilla INT NOT NULL,
    Correlativo INT NOT NULL,
    Nombre VARCHAR(255),
    PRIMARY KEY (Empresa, Plantilla, Correlativo)
) ENGINE = InnoDB;
CREATE TABLE preciofamilia (
    Empresa VARCHAR(3) NOT NULL,
    Familia VARCHAR(20) NOT NULL,
    Precio DOUBLE,
    Costo DOUBLE,
    PRIMARY KEY (Empresa, Familia)
) ENGINE = InnoDB;
CREATE TABLE correlativos (
    EMPRESA VARCHAR(3) NOT NULL,
    TIPO VARCHAR(20) NOT NULL,
    VALOR INT,
    PRIMARY KEY (EMPRESA, TIPO)
) ENGINE = InnoDB;
CREATE TABLE folios (
    EMPRESA VARCHAR(3) NOT NULL,
    TIPO VARCHAR(20) NOT NULL,
    EQUIPO VARCHAR(30) NOT NULL,
    ACTUAL INT,
    MAXIMO INT,
    PRIMARY KEY (EMPRESA, TIPO, EQUIPO)
) ENGINE = InnoDB;
CREATE TABLE periodos (
    EMPRESA VARCHAR(3) NOT NULL,
    SISTEMA VARCHAR(10) NOT NULL,
    PERIODO INT NOT NULL,
    MES01 BIT(1),
    MES02 BIT(1),
    MES03 BIT(1),
    MES04 BIT(1),
    MES05 BIT(1),
    MES06 BIT(1),
    MES07 BIT(1),
    MES08 BIT(1),
    MES09 BIT(1),
    MES10 BIT(1),
    MES11 BIT(1),
    MES12 BIT(1),
    PRIMARY KEY (EMPRESA, SISTEMA, PERIODO)
) ENGINE = InnoDB;
CREATE TABLE secuencia (
    EMPRESA VARCHAR(3),
    TIPOCOMP VARCHAR(10),
    DESDE INT,
    HASTA INT
) ENGINE = InnoDB;
-- Sin PK formal (igual que producción)
CREATE TABLE configuracuenta (
    Empresa VARCHAR(3),
    NivelNombre1 VARCHAR(30),
    NivelLargo1 INT,
    NivelNombre2 VARCHAR(30),
    NivelLargo2 INT,
    NivelNombre3 VARCHAR(30),
    NivelLargo3 INT,
    NivelNombre4 VARCHAR(30),
    NivelLargo4 INT,
    NivelNombre5 VARCHAR(30),
    NivelLargo5 INT
) ENGINE = InnoDB;
-- ============================================================
-- FASE B — Datos maestros operativos
-- ============================================================
CREATE TABLE articulos (
    EMPRESA VARCHAR(3) NOT NULL,
    Codigo_Articulo VARCHAR(20) NOT NULL,
    Descripcion VARCHAR(100),
    Comentario VARCHAR(255),
    Moneda_Compra VARCHAR(10),
    Moneda_venta VARCHAR(10),
    Unidad_Medida VARCHAR(10),
    Precio_Venta DOUBLE,
    Costo DOUBLE,
    Costo_Ult_Compra DOUBLE,
    Fecha_Ult_Compra DATETIME,
    Stock_Minimo DOUBLE,
    Stock_Maximo DOUBLE,
    Factor DOUBLE,
    Procedencia VARCHAR(1),
    Lotes BIT(1),
    Seriales BIT(1),
    Compras BIT(1),
    ControlaStock BIT(1),
    Plantilla INT,
    CodigoBarra VARCHAR(50),
    Activo BIT(1) DEFAULT 1,
    PRIMARY KEY (EMPRESA, Codigo_Articulo)
) ENGINE = InnoDB;
CREATE TABLE clientes (
    EMPRESA VARCHAR(3) NOT NULL,
    RUT_CLIENTE INT NOT NULL,
    DV_RUT VARCHAR(1),
    RAZON_SOCIAL VARCHAR(100),
    SIGLA VARCHAR(60),
    GIRO VARCHAR(50),
    DIRECCION VARCHAR(100),
    COMUNA VARCHAR(50),
    CIUDAD VARCHAR(50),
    TELEFONO VARCHAR(15),
    FAX VARCHAR(15),
    CORREO VARCHAR(50),
    CODIGO_VENDEDOR INT,
    CONDICION_PAGO INT,
    LISTA_PRECIO INT,
    CONTACTO VARCHAR(60),
    RUT_COMPRADOR VARCHAR(12),
    NOMBRE_COMPRADOR VARCHAR(50),
    CRED_MAXIMO DOUBLE,
    VIGEN_CREDITO DATETIME,
    POR_DEUDA DOUBLE,
    MAX_RETRASO INT,
    ULT_COMPRA DATETIME,
    BODEGA VARCHAR(20),
    PRIMARY KEY (EMPRESA, RUT_CLIENTE)
) ENGINE = InnoDB;
CREATE TABLE proveedores (
    EMPRESA VARCHAR(3) NOT NULL,
    RUT_PROVEEDOR INT NOT NULL,
    DV_RUT VARCHAR(1),
    RAZON_SOCIAL VARCHAR(100),
    SIGLA VARCHAR(60),
    GIRO VARCHAR(50),
    DIRECCION VARCHAR(100),
    COMUNA VARCHAR(50),
    CIUDAD VARCHAR(50),
    TELEFONO VARCHAR(15),
    FAX VARCHAR(15),
    CORREO VARCHAR(50),
    CODIGO_VENDEDOR INT,
    CONDICION_PAGO INT,
    LISTA_PRECIO INT,
    CONTACTO VARCHAR(60),
    CRED_MAXIMO DOUBLE,
    VIGEN_CREDITO DATETIME,
    POR_DEUDA DOUBLE,
    MAX_RETRASO INT,
    ULT_COMPRA DATETIME,
    PRIMARY KEY (EMPRESA, RUT_PROVEEDOR)
) ENGINE = InnoDB;
CREATE TABLE ctasctes (
    EMPRESA VARCHAR(3) NOT NULL,
    RUT_CTACTE INT NOT NULL,
    DIGITO VARCHAR(1),
    NOMBRE VARCHAR(100),
    DIRECCION VARCHAR(100),
    COMUNA VARCHAR(50),
    CIUDAD VARCHAR(50),
    TELEFONO VARCHAR(50),
    CONTACTO VARCHAR(50),
    FONO VARCHAR(50),
    FAX VARCHAR(50),
    CORREO VARCHAR(50),
    Banco VARCHAR(45),
    TipoCta VARCHAR(20),
    NroCta VARCHAR(20),
    PRIMARY KEY (EMPRESA, RUT_CTACTE)
) ENGINE = InnoDB;
CREATE TABLE proveebordado (
    EMPRESA VARCHAR(3),
    RUT INT,
    DV VARCHAR(1),
    NOMBRE VARCHAR(100),
    BANCO VARCHAR(50),
    TIPO_CUENTA VARCHAR(20),
    NRO_CUENTA VARCHAR(30),
    CONTACTO VARCHAR(60),
    TELEFONO VARCHAR(20),
    CORREO VARCHAR(80)
) ENGINE = InnoDB;
CREATE TABLE receptores (
    Empresa VARCHAR(3) NOT NULL,
    Receptor VARCHAR(40) NOT NULL,
    Correo VARCHAR(80),
    Equipo VARCHAR(20),
    PRIMARY KEY (Empresa, Receptor)
) ENGINE = InnoDB;
CREATE TABLE relacioncodigos (
    Empresa VARCHAR(3) NOT NULL,
    Cliente DOUBLE NOT NULL,
    CodigoCliente VARCHAR(20) NOT NULL,
    DescripCliente VARCHAR(100),
    CodigoInterno VARCHAR(20) NOT NULL,
    Modelo VARCHAR(45),
    Composicion VARCHAR(45),
    Tela VARCHAR(45),
    PRIMARY KEY (Empresa, Cliente, CodigoCliente)
) ENGINE = InnoDB;
CREATE TABLE documentovtas (
    EMPRESA VARCHAR(3) NOT NULL,
    TIPO_DOCUMENTO VARCHAR(10) NOT NULL,
    DESCRIPCION VARCHAR(60),
    APLICA_IVA BIT(1),
    ES_FACTURA BIT(1),
    ES_BOLETA BIT(1),
    ES_NOTA BIT(1),
    PRIMARY KEY (EMPRESA, TIPO_DOCUMENTO)
) ENGINE = InnoDB;
CREATE TABLE docucompra (
    EMPRESA VARCHAR(3) NOT NULL,
    TIPO_DOCUMENTO VARCHAR(10) NOT NULL,
    DESCRIPCION VARCHAR(60),
    APLICA_IVA BIT(1),
    PRIMARY KEY (EMPRESA, TIPO_DOCUMENTO)
) ENGINE = InnoDB;
CREATE TABLE activos (
    EMPRESA VARCHAR(3) NOT NULL,
    CODIGO VARCHAR(20) NOT NULL,
    DESCRIPCION VARCHAR(50),
    PRIMARY KEY (EMPRESA, CODIGO)
) ENGINE = InnoDB;
CREATE TABLE medidas_alternativas (
    Empresa VARCHAR(3) NOT NULL,
    Codigo_Articulo VARCHAR(20) NOT NULL,
    Unidad_medida VARCHAR(10) NOT NULL,
    Factor DOUBLE,
    PRIMARY KEY (Empresa, Codigo_Articulo, Unidad_medida)
) ENGINE = InnoDB;
-- USUARIOS Y ACCESOS
CREATE TABLE usuarios (
    EMPRESA VARCHAR(3) NOT NULL,
    RUT_USUARIO VARCHAR(15) NOT NULL,
    Sistema VARCHAR(10) NOT NULL,
    DIGITO VARCHAR(1),
    NOMBRE_USUARIO VARCHAR(50),
    CLAVE_USUARIO VARCHAR(50),
    -- Sin hash, igual que producción (no migrar al ERP)
    Vigencia BIT(1) DEFAULT 1,
    PRIMARY KEY (EMPRESA, RUT_USUARIO, Sistema)
) ENGINE = InnoDB;
-- accesos: 10 menus x 20 opciones = 200 columnas bit + 10 columnas Menu_01..10
CREATE TABLE accesos (
    Empresa VARCHAR(3) NOT NULL,
    Usuario VARCHAR(15) NOT NULL,
    Sistema VARCHAR(10) NOT NULL,
    Menu_01 BIT(1),
    Menu_02 BIT(1),
    Menu_03 BIT(1),
    Menu_04 BIT(1),
    Menu_05 BIT(1),
    Menu_06 BIT(1),
    Menu_07 BIT(1),
    Menu_08 BIT(1),
    Menu_09 BIT(1),
    Menu_10 BIT(1),
    M01_Op01 BIT(1),
    M01_Op02 BIT(1),
    M01_Op03 BIT(1),
    M01_Op04 BIT(1),
    M01_Op05 BIT(1),
    M01_Op06 BIT(1),
    M01_Op07 BIT(1),
    M01_Op08 BIT(1),
    M01_Op09 BIT(1),
    M01_Op10 BIT(1),
    M01_Op11 BIT(1),
    M01_Op12 BIT(1),
    M01_Op13 BIT(1),
    M01_Op14 BIT(1),
    M01_Op15 BIT(1),
    M01_Op16 BIT(1),
    M01_Op17 BIT(1),
    M01_Op18 BIT(1),
    M01_Op19 BIT(1),
    M01_Op20 BIT(1),
    M02_Op01 BIT(1),
    M02_Op02 BIT(1),
    M02_Op03 BIT(1),
    M02_Op04 BIT(1),
    M02_Op05 BIT(1),
    M02_Op06 BIT(1),
    M02_Op07 BIT(1),
    M02_Op08 BIT(1),
    M02_Op09 BIT(1),
    M02_Op10 BIT(1),
    M02_Op11 BIT(1),
    M02_Op12 BIT(1),
    M02_Op13 BIT(1),
    M02_Op14 BIT(1),
    M02_Op15 BIT(1),
    M02_Op16 BIT(1),
    M02_Op17 BIT(1),
    M02_Op18 BIT(1),
    M02_Op19 BIT(1),
    M02_Op20 BIT(1),
    M03_Op01 BIT(1),
    M03_Op02 BIT(1),
    M03_Op03 BIT(1),
    M03_Op04 BIT(1),
    M03_Op05 BIT(1),
    M03_Op06 BIT(1),
    M03_Op07 BIT(1),
    M03_Op08 BIT(1),
    M03_Op09 BIT(1),
    M03_Op10 BIT(1),
    M03_Op11 BIT(1),
    M03_Op12 BIT(1),
    M03_Op13 BIT(1),
    M03_Op14 BIT(1),
    M03_Op15 BIT(1),
    M03_Op16 BIT(1),
    M03_Op17 BIT(1),
    M03_Op18 BIT(1),
    M03_Op19 BIT(1),
    M03_Op20 BIT(1),
    M04_Op01 BIT(1),
    M04_Op02 BIT(1),
    M04_Op03 BIT(1),
    M04_Op04 BIT(1),
    M04_Op05 BIT(1),
    M04_Op06 BIT(1),
    M04_Op07 BIT(1),
    M04_Op08 BIT(1),
    M04_Op09 BIT(1),
    M04_Op10 BIT(1),
    M04_Op11 BIT(1),
    M04_Op12 BIT(1),
    M04_Op13 BIT(1),
    M04_Op14 BIT(1),
    M04_Op15 BIT(1),
    M04_Op16 BIT(1),
    M04_Op17 BIT(1),
    M04_Op18 BIT(1),
    M04_Op19 BIT(1),
    M04_Op20 BIT(1),
    M05_Op01 BIT(1),
    M05_Op02 BIT(1),
    M05_Op03 BIT(1),
    M05_Op04 BIT(1),
    M05_Op05 BIT(1),
    M05_Op06 BIT(1),
    M05_Op07 BIT(1),
    M05_Op08 BIT(1),
    M05_Op09 BIT(1),
    M05_Op10 BIT(1),
    M05_Op11 BIT(1),
    M05_Op12 BIT(1),
    M05_Op13 BIT(1),
    M05_Op14 BIT(1),
    M05_Op15 BIT(1),
    M05_Op16 BIT(1),
    M05_Op17 BIT(1),
    M05_Op18 BIT(1),
    M05_Op19 BIT(1),
    M05_Op20 BIT(1),
    M06_Op01 BIT(1),
    M06_Op02 BIT(1),
    M06_Op03 BIT(1),
    M06_Op04 BIT(1),
    M06_Op05 BIT(1),
    M06_Op06 BIT(1),
    M06_Op07 BIT(1),
    M06_Op08 BIT(1),
    M06_Op09 BIT(1),
    M06_Op10 BIT(1),
    M06_Op11 BIT(1),
    M06_Op12 BIT(1),
    M06_Op13 BIT(1),
    M06_Op14 BIT(1),
    M06_Op15 BIT(1),
    M06_Op16 BIT(1),
    M06_Op17 BIT(1),
    M06_Op18 BIT(1),
    M06_Op19 BIT(1),
    M06_Op20 BIT(1),
    M07_Op01 BIT(1),
    M07_Op02 BIT(1),
    M07_Op03 BIT(1),
    M07_Op04 BIT(1),
    M07_Op05 BIT(1),
    M07_Op06 BIT(1),
    M07_Op07 BIT(1),
    M07_Op08 BIT(1),
    M07_Op09 BIT(1),
    M07_Op10 BIT(1),
    M07_Op11 BIT(1),
    M07_Op12 BIT(1),
    M07_Op13 BIT(1),
    M07_Op14 BIT(1),
    M07_Op15 BIT(1),
    M07_Op16 BIT(1),
    M07_Op17 BIT(1),
    M07_Op18 BIT(1),
    M07_Op19 BIT(1),
    M07_Op20 BIT(1),
    M08_Op01 BIT(1),
    M08_Op02 BIT(1),
    M08_Op03 BIT(1),
    M08_Op04 BIT(1),
    M08_Op05 BIT(1),
    M08_Op06 BIT(1),
    M08_Op07 BIT(1),
    M08_Op08 BIT(1),
    M08_Op09 BIT(1),
    M08_Op10 BIT(1),
    M08_Op11 BIT(1),
    M08_Op12 BIT(1),
    M08_Op13 BIT(1),
    M08_Op14 BIT(1),
    M08_Op15 BIT(1),
    M08_Op16 BIT(1),
    M08_Op17 BIT(1),
    M08_Op18 BIT(1),
    M08_Op19 BIT(1),
    M08_Op20 BIT(1),
    M09_Op01 BIT(1),
    M09_Op02 BIT(1),
    M09_Op03 BIT(1),
    M09_Op04 BIT(1),
    M09_Op05 BIT(1),
    M09_Op06 BIT(1),
    M09_Op07 BIT(1),
    M09_Op08 BIT(1),
    M09_Op09 BIT(1),
    M09_Op10 BIT(1),
    M09_Op11 BIT(1),
    M09_Op12 BIT(1),
    M09_Op13 BIT(1),
    M09_Op14 BIT(1),
    M09_Op15 BIT(1),
    M09_Op16 BIT(1),
    M09_Op17 BIT(1),
    M09_Op18 BIT(1),
    M09_Op19 BIT(1),
    M09_Op20 BIT(1),
    M10_Op01 BIT(1),
    M10_Op02 BIT(1),
    M10_Op03 BIT(1),
    M10_Op04 BIT(1),
    M10_Op05 BIT(1),
    M10_Op06 BIT(1),
    M10_Op07 BIT(1),
    M10_Op08 BIT(1),
    M10_Op09 BIT(1),
    M10_Op10 BIT(1),
    M10_Op11 BIT(1),
    M10_Op12 BIT(1),
    M10_Op13 BIT(1),
    M10_Op14 BIT(1),
    M10_Op15 BIT(1),
    M10_Op16 BIT(1),
    M10_Op17 BIT(1),
    M10_Op18 BIT(1),
    M10_Op19 BIT(1),
    M10_Op20 BIT(1),
    PRIMARY KEY (Empresa, Usuario, Sistema)
) ENGINE = InnoDB;
SELECT 'PARTE 1 OK: DB + Fases A y B creadas.' AS status;