# ===============================
# APP
# ===============================
spring.application.name=transitorio
server.port=8015

# ===============================
# PERFIL ACTIVO
# ===============================
# dev  -> entorno local
# prod -> servidor real
spring.profiles.active=dev

# ===============================
# CONFIGURACION GLOBAL
# ===============================

# --- Encoding
spring.servlet.encoding.charset=UTF-8
spring.servlet.encoding.enabled=true
spring.servlet.encoding.force=true

# --- Timezone
spring.jackson.time-zone=America/Santiago

# --- Logging
logging.level.root=INFO
logging.level.org.hibernate.SQL=DEBUG


# ===============================
# BASE DE DATOS - LEGACY (MySQL)
# ===============================
legacy.datasource.url=jdbc:mysql://localhost:3306/antuan_test
legacy.datasource.username=antuan_app
legacy.datasource.password=Antuan123*
legacy.datasource.driver-class-name=com.mysql.cj.jdbc.Driver

# ===============================
# BASE DE DATOS - ERP (Postgres)
# ===============================
# Nota: Configuración preparada para el nuevo backend
erp.datasource.url=jdbc:postgresql://localhost:5432/antuandb
erp.datasource.username=postgres
erp.datasource.password=postgres
erp.datasource.driver-class-name=org.postgresql.Driver

# ===============================
# JPA / HIBERNATE
# ===============================
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.MySQLDialect


# ===============================
# DOCS
# ===============================
# Swagger:
# http://localhost:8015/swagger-ui/index.html